### PR TITLE
Feature separate wg wgps

### PR DESCRIPTION
**Pull request by AiyionPrime**
This is my idea on how to implement the respondd related changes as two software entries.
Please do not merge this, I've not tested it successfully, yet.

I hope we can discuss the idea at the beginning of the evening in order to build a new firmware before midnight.

This reimplements the wgpeerselector-respondd-code in order to provide a response like this:

```
[...]
      },
      "wireguard": {
        "enabled": true,
        "public_key": "0000000000000000000000000000000000000000000=",
        "version": "v1.0.20210124"
      },
      "wgpeerselector": {
        "enabled": true,
        "version": "v1"
      }
    },
[...]
```

The modular approach will likely promote a greater acceptance of your changes in other communities and projects.

@genofire We'll discuss this approach later today; I'll update https://github.com/FreifunkBremen/yanic/pull/187 and https://github.com/FreifunkBremen/yanic/pull/193 according to our conclusion later.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
This compiles successfully on syntax level;
but lacks wgpeerselector for now.
I'll be in mumble in two hours again, then with microphone;
maybe we can discuss this pr properly then.

**Comment by AiyionPrime** [comment]
@lemoer tested on one node with a patched yanic:
`curl https://harvester.ffh.zone/nodes.json | jq '(.nodes[] | select(.nodeinfo.node_id == "44d1fa59f87d"))' | less`

**Comment by AiyionPrime** [comment]
@lemoer There are currently twelve devices testing this pr.
Is there something missing?
The only devices offline are three of @cawi2001, which are really offline, as well as one of mine, which is barely connected via wifi.

**Comment by AiyionPrime** [comment]
Squashed the eight commits into one,
history remains at https://github.com/AiyionPrime/gluon/tree/feature_separate_wg_wgps_unsquashed

**Comment by AiyionPrime** [comment]
@lemoer Is there anything left to provide?

**Comment by lemoer** [comment]
No, nothing left. This is now part of https://github.com/freifunk-gluon/gluon/pull/2168 .

**Pull request closed without merging**
